name: insiders-build
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  insiders-build:
    strategy:
      matrix:
        os: [win-code-sign, mac-build2, ubuntu-latest]
        include:
          - os: win-code-sign
            build: |
              # Inject git SHA and date into package.json
              $GIT_SHA = (git rev-parse --short HEAD)
              $DATE_STR = (Get-Date -Format "yyyy-MMM-dd")
              (Get-Content package.json) -replace '"version": "(.*?)"', ('"version": "$1_' + $DATE_STR + '_' + $GIT_SHA + '"') | Set-Content package.json

              ./node_modules/.bin/esbuild src/ctrl-q.js --bundle --outfile=build.cjs --format=cjs --platform=node --target=node24 --inject:./src/lib/util/import-meta-url.js --define:import.meta.url=import_meta_url
              node --experimental-sea-config sea-config.json
              node -e "require('fs').copyFileSync(process.execPath, 'ctrl-q.exe')"

              # Remove the signature from the executable
              $processOptions1 = @{
                FilePath = "C:\Program Files (x86)/Windows Kits/10/bin/10.0.22621.0/x64/signtool.exe"
                Wait = $true
                ArgumentList = "remove", "/s", "./${env:DIST_FILE_NAME}.exe"
                WorkingDirectory = "."
                NoNewWindow = $true
              }
              Start-Process @processOptions1

              npx postject ctrl-q.exe NODE_SEA_BLOB sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2

              dir

              # Sign the executable
              # 1st signing
              $processOptions1 = @{
                FilePath = "C:\Program Files (x86)/Windows Kits/10/bin/10.0.22621.0/x64/signtool.exe"
                Wait = $true
                ArgumentList = "sign", "/sha1", "$env:CODESIGN_WIN_THUMBPRINT", "/tr", "http://time.certum.pl", "/td", "sha256", "/fd", "sha1", "/v", "./${env:DIST_FILE_NAME}.exe"
                WorkingDirectory = "."
                NoNewWindow = $true
              }
              Start-Process @processOptions1

              # 2nd signing
              $processOptions2 = @{
                FilePath = "C:\Program Files (x86)/Windows Kits/10/bin/10.0.22621.0/x64/signtool.exe"
                Wait = $true
                ArgumentList = "sign", "/sha1", "$env:CODESIGN_WIN_THUMBPRINT", "/tr", "http://time.certum.pl", "/td", "sha256", "/fd", "sha256", "/v", "./${env:DIST_FILE_NAME}.exe"
                WorkingDirectory = "."
                NoNewWindow = $true
              }
              Start-Process @processOptions2

              # Create insider's build zip
              $compress = @{
                Path = "./${env:DIST_FILE_NAME}.exe"
                CompressionLevel = "Fastest"
                DestinationPath = "${env:DIST_FILE_NAME}--win-x64--${{ github.sha }}.zip"
              }

              Compress-Archive @compress

            artifact_insider: ctrl-q--win-x64--${{ github.sha }}.zip
          - os: mac-build2
            build: |
              # Inject git SHA and date into package.json
              GIT_SHA=$(git rev-parse --short HEAD)
              DATE_STR=$(date +"%Y-%b-%d")
              VERSION=$(grep -o '"version": "[^"]*"' package.json | cut -d'"' -f4)
              sed -i '' "s/\"version\": \".*\"/\"version\": \"${VERSION}_${DATE_STR}_${GIT_SHA}\"/" package.json

              ./node_modules/.bin/esbuild src/ctrl-q.js --bundle --outfile=build.cjs --format=cjs --platform=node --target=node24 --inject:./src/lib/util/import-meta-url.js --define:import.meta.url=import_meta_url
              node --experimental-sea-config sea-config.json
              cp $(command -v node) ${DIST_FILE_NAME}
              codesign --remove-signature ${DIST_FILE_NAME}
              npx postject ctrl-q NODE_SEA_BLOB sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2 --macho-segment-name NODE_SEA

              security delete-keychain build.keychain || true

              pwd
              ls -la

              # -------------------
              # Turn our base64-encoded certificate back to a regular .p12 file
              echo "DEBUG: Decoding certificate from base64"
              echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12

              export KEYCHAIN_NAME="build.keychain"

              # -------------------
              # We need to create a new keychain, otherwise using the certificate will prompt
              # with a UI dialog asking for the certificate password, which we can't
              # use in a headless CI environment

              echo "DEBUG: Creating new keychain"
              security create-keychain -p "$MACOS_CI_KEYCHAIN_PWD" "${KEYCHAIN_NAME}"

              echo "DEBUG: Getting current keychain list"
              OLD_KEYCHAIN_NAMES=$(security list-keychains -d user | sed -e 's/"//g' | xargs)
              echo "DEBUG: Current keychains: ${OLD_KEYCHAIN_NAMES}"

              echo "DEBUG: Setting keychain search list"
              security list-keychains -d user -s "${KEYCHAIN_NAME}" ${OLD_KEYCHAIN_NAMES}

              echo "DEBUG: Getting current default keychain"
              DEFAULT_KEYCHAIN=$(security default-keychain -d user | sed -e 's/"//g' | xargs)
              echo "DEBUG: Default keychain is: ${DEFAULT_KEYCHAIN}"

              echo "DEBUG: Setting our keychain as default"
              security default-keychain -d user -s "${KEYCHAIN_NAME}"

              echo "DEBUG: Unlocking keychain"
              security unlock-keychain -p "$MACOS_CI_KEYCHAIN_PWD" "${KEYCHAIN_NAME}"

              echo "DEBUG: Importing certificate into keychain"
              security import certificate.p12 -k "${KEYCHAIN_NAME}" -P "$MACOS_CERTIFICATE_PWD" -T /usr/bin/codesign -A

              echo "DEBUG: Importing Apple Developer ID G2 intermediate CA"
              curl -L -s -o DeveloperIDG2CA.cer https://www.apple.com/certificateauthority/DeveloperIDG2CA.cer
              security import DeveloperIDG2CA.cer -k "${KEYCHAIN_NAME}"
              rm DeveloperIDG2CA.cer

              echo "DEBUG: Setting keychain timeout to prevent locking"
              security set-keychain-settings -t 3600 -l "${KEYCHAIN_NAME}"

              echo "DEBUG: Setting key partition list"
              security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$MACOS_CI_KEYCHAIN_PWD" "${KEYCHAIN_NAME}"

              echo "DEBUG: Performing codesign operation"
              codesign --force -s "$MACOS_CERTIFICATE_NAME" -v "./${DIST_FILE_NAME}" --deep --strict --options=runtime --timestamp --entitlements ./release-config/${DIST_FILE_NAME}.entitlements

              echo "DEBUG: Verifying code signature"
              codesign -vvv --deep --strict "./${DIST_FILE_NAME}"

              # -------------------
              # Notarize
              # Store the notarization credentials so that we can prevent a UI password dialog from blocking the CI
              echo "Create keychain profile"
              KEYCHAIN_PATH=~/Library/Keychains/${KEYCHAIN_NAME}-db
              echo "DEBUG: Using keychain at path: ${KEYCHAIN_PATH}"
              xcrun notarytool store-credentials "notarytool-profile" --apple-id "$PROD_MACOS_NOTARIZATION_APPLE_ID" --team-id "$PROD_MACOS_NOTARIZATION_TEAM_ID" --password "$PROD_MACOS_NOTARIZATION_PWD" --keychain "${KEYCHAIN_PATH}"

              # -------------------
              # Create archive for notarization
              echo "Creating temp notarization archive for insider build"
              zip -r "./${DIST_FILE_NAME}--macos-arm64--${{ github.sha }}.zip" "./${DIST_FILE_NAME}" -x "*.DS_Store"

              echo "Notarize insider app"
              xcrun notarytool submit "./${DIST_FILE_NAME}--macos-arm64--${{ github.sha }}.zip" --keychain-profile "notarytool-profile" --wait --keychain "${KEYCHAIN_PATH}"

              echo "DEBUG: Restoring original default keychain"
              security default-keychain -d user -s "$DEFAULT_KEYCHAIN" || echo "WARNING: Failed to restore default keychain, continuing anyway"

              echo "DEBUG: Restoring original keychain list"
              security list-keychains -d user -s ${OLD_KEYCHAIN_NAMES} || echo "WARNING: Failed to restore keychain list, continuing anyway"

              # -------------------
              # Clean up
              security delete-keychain build.keychain
              rm build.cjs certificate.p12

            artifact_insider: ctrl-q--macos-arm64--${{ github.sha }}.zip

          - os: ubuntu-latest
            build: |
              # Inject git SHA and date into package.json
              GIT_SHA=$(git rev-parse --short HEAD)
              DATE_STR=$(date +"%Y-%b-%d")
              VERSION=$(grep -o '"version": "[^"]*"' package.json | cut -d'"' -f4)
              sed -i "s/\"version\": \".*\"/\"version\": \"${VERSION}_${DATE_STR}_${GIT_SHA}\"/" package.json

              ./node_modules/.bin/esbuild src/ctrl-q.js --bundle --outfile=build.cjs --format=cjs --platform=node --target=node24 --inject:./src/lib/util/import-meta-url.js --define:import.meta.url=import_meta_url
              node --experimental-sea-config sea-config.json
              cp $(command -v node) ${DIST_FILE_NAME}
              npx postject ctrl-q NODE_SEA_BLOB sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2

              chmod +x ${DIST_FILE_NAME}

              # Compress insider's build
              tar -czf "${DIST_FILE_NAME}--linux-x64--${{ github.sha }}.tgz" "${DIST_FILE_NAME}"
              ls -la
            artifact_insider: ctrl-q--linux-x64--${{ github.sha }}.tgz
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5.0.0, pinned on 2025-11-14

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.0.0, pinned on 2025-11-14
        with:
          node-version: 24

      - name: Install tool for creating stand-alone executables
        run: |
          npm install --save-exact esbuild

      - name: Install dependencies
        run: |
          pwd
          npm ci --include=prod

      - name: Run Snyk to check for vulnerabilities
        if: |
          github.repository_owner == 'ptarmiganlabs' &&
          matrix.os == 'ubuntu-latest'
        continue-on-error: true
        uses: snyk/actions/node@9adf32b1121593767fc3c057af55b55db032dc04 # master, pinned on 2025-11-14
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=./package.json --sarif-file-output=snyk.sarif

      - name: Upload Snyk result to GitHub Code Scanning
        if: |
          github.repository_owner == 'ptarmiganlabs' &&
          matrix.os == 'ubuntu-latest'
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@0d579ffd059c29b07949a3cce3983f0780820c98 # v4.32.6, pinned on 2025-11-14
        with:
          sarif_file: snyk.sarif

      - name: Create binaries
        env:
          DIST_FILE_NAME: ctrl-q
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_PAT }}
          MACOS_CERTIFICATE: ${{ secrets.PROD_MACOS_CERTIFICATE_BASE64_CODESIGN }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.PROD_MACOS_CERTIFICATE_CODESIGN_PWD }}
          MACOS_CERTIFICATE_NAME: ${{ secrets.PROD_MACOS_CERTIFICATE_CODESIGN_NAME }}
          MACOS_CI_KEYCHAIN_PWD: ${{ secrets.PROD_MACOS_CI_KEYCHAIN_PWD }}
          PROD_MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_APPLE_ID }}
          PROD_MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_TEAM_ID }}
          PROD_MACOS_NOTARIZATION_PWD: ${{ secrets.PROD_MACOS_NOTARIZATION_PWD }}
          CODESIGN_WIN_THUMBPRINT: ${{ secrets.WIN_CODESIGN_THUMBPRINT}}
        run: |
          pwd
          ${{ matrix.build }}

      - name: Upload insider build artifacts to GitHub
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v5.0.0, pinned on 2025-11-14
        with:
          name: ${{ matrix.artifact_insider }}
          path: ${{ matrix.artifact_insider }}
